### ISSUE TITLE
Como usuario anónimo, debo poder loguearme con Facebook

### ISSUE THREAD

**Issue by norchow** [UTN-FRBA-Mobile/KeepApp#1]
Puede ser con Firebase directamente

**Comment by julisalis** [comment]
Ya funciona login con email/password y con fb.
Faltaria hacer un perfil de usuario para poder linkear una cuenta de fb despues de haberla creado con email/pass.
Ya esta hecho el codigo para redireccionar a la activity siguiente si ya estabas logueado al abrirla, pero lo deje comentado para seguir probando el inicio de sesion (porque todavia no tenemos un boton de cerrar sesion).
